

                09Welcome to 0cHPC09 Installer!07
0a
                          .-=-.          .--.
              __        .'     '.       /  " )
      _     .'  '.     /   .-.   \     /  .-'0c\0a
     ( \   / .-.  \   /   /   \   \   /  /    0c^0a
      \ `-` /   \  `-'   /     \   `-`  /
       `-.-`     '.____.'       `.____.'
07

Enter number of the Operation System you wish to install:

0. Boot Local Machine

1. CENTOS-7 CentOS 7.0 64 bit 



05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
